# Plugins
plugins:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "ResBaz Sydney 2021"
email: "resbazsyd@gmail.com"
description: "A conference promoting digital literacy and skill-sharing for researchers"
baseurl: "/resbaz2021/sydney"
url: "https://resbaz.github.io"
permalink: "/news/:title"
googleAnalyticsTrackingId: "xxxxxxxx"
googleAnalyticsSiteUrl: "sydney.resbaz.com.au"
siteVerification: "xxxxxxx"

# Organizer Info
organizerName: "ResBaz Sydney"
organizerAlternateName: "ResBaz Sydney"
organizerDescription: "The organisers of ResBaz Sydney"
organizerEmail: "resbazsyd@gmail.com"
organizerLogo: "/img/seo/ResBaz_transparent_cropped.png"
organizerLink: "https://resbaz.github.io/resbaz2021/sydney"


# Head
metaKeywords: "event, research, library, digital, skills, eresearch"
twitterAccount: "ResBazSyd"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/about/", text: "About"}
 - {permalink: "/news/", text: "News"}
 - {permalink: "/getinvolved/", text: "Get involved"}
 - {permalink: "/program/", text: "Program"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/code/", text: "Code of Conduct"}
bottomNavigationLinks:
 - {permalink: "/getinvolved/", text: "Get involved"}
 - {link: "http://eepurl.com/hGWsUH", text: "Join our mailing list"}
rightNavigationButtons:
 - {permalink: "/getinvolved/", text: "Get involved"}
 - {link: "http://eepurl.com/hGWsUH", text: "Join our mailing list"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "ResBaz Sydney 2021"
eventDate: "Tue 23-Thu 25 November 2021"
heroButtons:
 - {permalink: "/getinvolved/", text: "Get involved"}

# About Block
aboutTitle: "About ResBaz"
aboutBlock:
 - {title: "Conference",image: "resbaz_logo.png", text: "ResBaz Sydney 2021 will be a multi stream online event Tuesday 23-Thursday 25 November 2021. The program will feature key stories (like keynotes, but with a narrative!), workshops, short talks, demonstrations and lots of opportunities to find out about next gen tech and tools for researchers. Our program has dedicated streams for Compute, Humanities and Social Science, and Survey / Data Collection, as well as two streams for introductory programming skills, which are open to all, regardless of skill level or discipline. Lots of breaks, lots of opportunities to find your people across institutions and disciplines, and plenty of neat tricks and hacks to level up on your nerd skills." }



# Rockstar Speakers Block
rockstarSpeakersImage: "cloud_genomics.jpg"
rockstarSpeakersCount: 3
rockstarSpeakersTitle: "Key Stories"
rockstarSpeakersButtonText: "See all speakers"

# Statistic Block
statisticBlockImage: "mac2018_hall2.jpg"
statisticBlock:
 - {count: "58", specialCharacter: "", info: "speakers"}
 - {count: "49", specialCharacter: "", info: "sessions"}
 - {count: "50", specialCharacter: "+", info: "hours", detail: "of researcher training"}
 - {count: "5", specialCharacter: "", info: "parallel tracks"}

# Latest News Block
latestNewsTitle: "Latest news"


# Past events Block
pastBlockTitle: "ResBaz 2019"
pastBigImage: audience.jpg 
pastSmallImage1: genomics.jpg
pastSmallImage2: jasper.jpg
pastSmallImage3: carpentries.jpg


# Tweets Feed Block
tweetsFeedImage: "nametags.jpg"
tweetsFeedTitle: "Twitter"
twitterHashTag: "resbazsyd"
twitterFeed: "http://twitter.com/ResBazSyd"

# Partners Block
organisersTitle: "Organisers"


# Footer
socialLinks:
 - {link: "https://twitter.com/ResBazSyd", icon: "twitter"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Contacts"
  links:
   - {link: "mailto:resbazsyd@gmail.com", text: "resbazsyd@gmail.com"}
 -
  title: "Code of Conduct"
  links:
   - {permalink: "/code/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: false

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "Volunteers"
aboutUs: "We'd like to thank all of the dedicated volunteers who have made ResBaz Sydney 2021 possible!"

