# Plugins
plugins:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "ResBaz Sydney 2023"
email: "resbazsyd@gmail.com"
description: "A conference promoting digital literacy and skill-sharing for researchers"
baseurl: "/resbaz2023syd"
url: "https://resbaz.github.io"
permalink: "/news/:title"
googleAnalyticsTrackingId: "xxxxxxxx"
googleAnalyticsSiteUrl: "sydney.resbaz.com.au"
siteVerification: "xxxxxxx"

# Workshop registration note

workshopRegisterNote: "<strong>Note</strong> you will need to register separately for this workshop"

# Organizer Info
organizerName: "ResBaz Sydney"
organizerAlternateName: "ResBaz Sydney"
organizerDescription: "The organisers of ResBaz Sydney"
organizerEmail: "resbazsyd@gmail.com"
organizerLogo: "/img/seo/ResBaz_transparent_cropped.png"
organizerLink: "https://resbaz.github.io/resbaz2023syd"


# Head
metaKeywords: "event, research, library, digital, skills, eresearch"
twitterAccount: "ResBazSyd"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/about/", text: "About"}
 # - {permalink: "/news/", text: "News"}
 # - {permalink: "/posters/", text: "Posters"}
 # - {permalink: "/program/", text: "Program"}
 # - {permalink: "/speakers/", text: "Speakers"}
 # - {permalink: "/code/", text: "Code of Conduct"}
# bottomNavigationLinks:
 # - {permalink: "/program/", text: "Register here"}
 # - {permalink: "/posters/", text: "Posters"}
# rightNavigationButtons:
 # - {permalink: "/program/", text: "Register here"}
 # - {permalink: "/posters/", text: "Posters"}

# Hero Block
heroImage: "usyd-reflection.jpg"
heroTitle: "<b>ResBaz Sydney 2023</b>"
eventDate: "<b>Tue 26-Thu 28 September</b>"
heroButtons:
 - {link: "https://docs.google.com/forms/d/1dbudJSN_5iBqa8gJMKRX0JpyopvOhmlgkQwiNk15EaY/", text: "Join the mailing list"}

# About Block
aboutTitle: "About ResBaz"
aboutBlock:
 - {title: "Conference",image: "resbaz_logo.png", text: "<p>The Research Bazaar is a worldwide festival promoting the digital literacy at the centre of modern research. Throughout 2023, events will be held at a number of university campuses around the world.</p><p>ResBaz Sydney 2023 will be a face-to-face event hosted by the University of Sydney where researchers from many different disciplines will come together to share their knowledge and develop skills in the latest digital platforms and tools. The program will feature keynotes, workshops, short talks, demonstrations and lots of opportunities to find out about the next generation of technology.</p><p>Who should attend? Researchers at ALL levels from ALL disciplines. PhD candidates, research Masters students and early career researchers are especially encouraged to attend. Research technologists and research software engineers who support researchers to do their job should also come along! Sessions at this year's ResBaz will offer a brief practical introduction to a broad selection of topics and tools related to digital research practice relevant across the disciplines. For examples of the sorts of training which ResBaz offers, you can visit the <a href=\"https://resbaz.github.io/resbaz2021/sydney/program/\"> 2021 programme.</a></p><p>For updates, please <a href=\"https://docs.google.com/forms/d/1dbudJSN_5iBqa8gJMKRX0JpyopvOhmlgkQwiNk15EaY/\">sign up for our mailing list</a></p>" }



# Rockstar Speakers Block
rockstarSpeakersImage: "cloud_genomics.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Key Stories"
rockstarSpeakersButtonText: "See all speakers"

# Statistic Block
statisticBlockImage: "mac2018_hall2.jpg"
statisticBlock:
 - {count: "58", specialCharacter: "", info: "presenters"}
 - {count: "49", specialCharacter: "", info: "sessions"}
 - {count: "50", specialCharacter: "+", info: "hours", detail: "of researcher training"}
 - {count: "5", specialCharacter: "", info: "parallel tracks"}

# Latest News Block
latestNewsTitle: "Latest news"


# Past events Block
pastBlockTitle: "ResBaz 2021"
pastBigImage: audience.jpg 
pastSmallImage1: genomics.jpg
pastSmallImage2: jasper.jpg
pastSmallImage3: carpentries.jpg


# Tweets Feed Block
tweetsFeedImage: "nametags.jpg"
tweetsFeedTitle: "Twitter"
twitterHashTag: "resbazsyd"
twitterFeed: "http://twitter.com/ResBazSyd"

# Partners Block
organisersTitle: "Organisers"


# Footer
socialLinks:
 - {link: "https://twitter.com/ResBazSyd", icon: "twitter"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Contacts"
  links:
   - {link: "mailto:resbazsyd@gmail.com", text: "resbazsyd@gmail.com"}
 # -
 #  title: "Code of Conduct"
 #  links:
 #   - {permalink: "/code/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: false

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "Volunteers"
aboutUs: "We'd like to thank all of the dedicated volunteers who have made ResBaz Sydney 2023 possible!"

